### ISSUE TITLE
Lack of necessary data

### ISSUE THREAD

**Issue by anbo225** [ahmedaley/SpotWeb#1]
hi, @ahmedaley, I am trying to run "MultiPeriodOptimizationSpotWebSimForTestbedExperiment.ipynb". But it seems that this project lack of necessary data. Also it would be nice to have  a  dependency package version specification.

**Comment by ahmedaley** [comment]
Hi,
As mentioned in the readme, we took down parts of the code to clean it up. Will update you once I have uploaded everything. For now, I will make the project private until all the code is online. I expect to bring it online in a week.

Sorry for that!

**Comment by ahmedaley** [comment]
Hi,
We have now released the code and data again after a cleanup. Sorry it took so long to get this done, but we opted for adding more documentations.

Please let me know if you still lack any data. Also, please note that some references to some files might need some changes based on your setup.
